datasus_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: [SUA_CONTA_DO_SNOWFLAKE]
      user: [SEU_USUARIO]
      password: [SUA_SENHA]
      role: [SUA_ROLE]                   # Ex: SYSADMIN
      warehouse: [SEU_WAREHOUSE]
      database: DATASUS_DB
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False